### ISSUE TITLE
Broken Download URL

### ISSUE THREAD

**Issue by tajmone** [thoni56/cgreen-cygport#1]
While trying to port this script to MSYS2 I've noticed that the `SRC_URI` link in [`cgreen.cygport`][cgreen.cygport] is broken:

```make
# source and patch files
SRC_URI=https://github.com/cgreen-devs/cgreen/archive/v1.0.0.tar.gz
```

Trying to open that link leads to a 404 error:

- https://github.com/cgreen-devs/cgreen/archive/v1.0.0.tar.gz

The problem is the extra `v` before `1.0.0.tar.gz`:

- https://github.com/cgreen-devs/cgreen/archive/1.0.0.tar.gz

Or, for an up-to-date versions:

- https://github.com/cgreen-devs/cgreen/archive/1.1.0.tar.gz

[cgreen.cygport]: https://github.com/cgreen-devs/cgreen-cygport/blob/master/cgreen.cygport#L24

**Comment by thoni56** [comment]
Fixed, thanks.
